
var op_template_size = 4;
var op_template_dates = new Array(op_template_size);
op_template_dates[0]="1m";
op_template_dates[1]="1q";
op_template_dates[2]="1y";
op_template_dates[3]="5y";
var op_template_graph=new Array(op_template_size);
var op_template_button_hover=new Array(op_template_size);
var op_template_buttons=new Array(op_template_size);
if (document.images){
 for(var i=0;i<op_template_size;i++){
  op_template_graph[i]=new Image(200,100);
  op_template_graph[i].src = "//oil-price.net/"+op_template_dates[i]+"_small.gif";
  op_template_button_hover[i] = new Image(25, 20);
  op_template_button_hover[i].src = "//oil-price.net/TABLE2/static/hover_"+op_template_dates[i]+".png";
  op_template_buttons[i] = new Image(25, 20);
  op_template_buttons[i].src = "//oil-price.net/TABLE2/static/button_"+op_template_dates[i]+".png";
  }
}
var op_template_current_but=0;
function op_template_showGraph(id){
 document.getElementById("op_template_button_"+op_template_current_but).src=op_template_buttons[op_template_current_but].src;
 document.getElementById("op_template_graph").src=op_template_graph[id].src;
 document.getElementById("op_template_button_"+id).src=op_template_button_hover[id].src;
 op_template_current_but=id;
 return true;
};
document.writeln('<style>.oilpricenettable2 {border-collapse: separate; border-spacing: 2px;} .oilpricenettable2 td {padding:1px;}<\/style>');
document.writeln('<table class=\"oilpricenettable2\" summary=\"Crude oil and commodity prices (c) http://oil-price.net\" style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12px; background-color:#efefef; border-collapse: collapse; text-align: left; border: 1px solid #000000; padding:0px; border-spacing:0px;\">');
document.writeln('<tbody style=\"padding:0px;\">');
document.writeln('<tr style=\"padding:0px;\">');
document.writeln('<td style=\"padding:0px;\">');
document.writeln('<table class=\"oilpricenettable2\" style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12px; background-color:#efefef; text-align: left; border: 0px; padding:0px; \" width=100%>');
document.writeln('<tbody style=\"padding:0px;\">');
document.writeln('<tr><td style=\"background-color:#cecfce; font-size: 18px; font-weight: bold; color: #000000 text-align: left; white-space: nowrap\" colspan=4 align=\"center\">');
document.writeln('<span style=\"color: #000000\">WTI Crude Oil<\/span><\/td>');
document.writeln('<\/tr>');
document.writeln('<tr>');
document.writeln('<td style=\"font-size: 22px; font-weight: bold; color: #000000 text-align: left; white-space: nowrap\" >');
document.writeln('<span style=\"color: #000000\">$79.98<\/span>');
document.writeln('<\/td>');
document.writeln('<td style=\"font-size: 16px; font-weight: bold; color: red; text-align: left; white-space: nowrap\">');
document.writeln('&#9660;-1.24');
document.writeln('<\/td>');
document.writeln('<td>&nbsp; <\/td>');
document.writeln('<td style=\"font-size: 16px; font-weight: bold; color: red; text-align: left; white-space: nowrap\">');
document.writeln('-1.55%');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<tr><td style=\"font-size: 9px; font-weight: bold; color: #FFFFFF text-align: left; white-space: nowrap\" colspan=4>');
document.writeln('<span style=\"color: #000000\">2022.12.04 end-of-day<\/span>');
document.writeln('<\/td><\/tr>');
document.writeln('<\/tbody>');
document.writeln('<\/table>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<tr>');
document.writeln('<td>');
document.writeln('<table class=\"oilpricenettable2\" style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12px; background-color:#efefef; border-collapse: collapse; text-align: left; border: 0px; padding:0px\">');
document.writeln('<tbody style=\"padding:0px;\">');
document.writeln('<tr style=\"padding:0px;\" valign=center><td style=\"padding:0px;\" align=center >');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en\">');
document.writeln('<img style=\"border:0px;\" src=\"//oil-price.net/1m_small.gif\" id=\"op_template_graph\" border=0>');
document.writeln('<\/a>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<tr>');
document.writeln('<td>');
document.writeln('<table class=\"oilpricenettable2\" style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12px; background-color:#efefef; border-collapse: collapse; text-align: left; border: 0px; padding:0px\" width=100% >');
document.writeln('<tbody style=\"padding:0px;\">');
document.writeln('<tr><td>');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en\" onMouseOver=\"op_template_showGraph(0);\"><img style=\"border:0px;\" src=\"//oil-price.net/TABLE2/static/hover_1m.png\" border=0 id=\"op_template_button_0\"><\/a>');
document.writeln('<\/td>');
document.writeln('<td>');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en\" onMouseOver=\"op_template_showGraph(1);\"><img style=\"border:0px;\" src=\"//oil-price.net/TABLE2/static/button_1q.png\" border=0 id=\"op_template_button_1\"><\/a>');
document.writeln('<\/td>');
document.writeln('<td>');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en\" onMouseOver=\"op_template_showGraph(2);\"><img style=\"border:0px;\" src=\"//oil-price.net/TABLE2/static/button_1y.png\" border=0 id=\"op_template_button_2\"><\/a>');
document.writeln('<\/td>');
document.writeln('<td>');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en\" onMouseOver=\"op_template_showGraph(3);\"><img style=\"border:0px;\" src=\"//oil-price.net/TABLE2/static/button_5y.png\" border=0 id=\"op_template_button_3\"><\/a>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<\/tbody>');
document.writeln('<\/table>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<\/tbody>');
document.writeln('<\/table>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<\/tbody>');
document.writeln('<\/table>');

