
var large_ng_size = 4;
var large_ng_dates = new Array(large_ng_size);
large_ng_dates[0]="1m";
large_ng_dates[1]="1q";
large_ng_dates[2]="1y";
large_ng_dates[3]="5y";
var large_ng_graph=new Array(large_ng_size);
var large_ng_button_hover=new Array(large_ng_size);
var large_ng_buttons=new Array(large_ng_size);
if (document.images){
 for(var i=0;i<large_ng_size;i++){
  large_ng_graph[i]=new Image(200,100);
  large_ng_graph[i].src = "//oil-price.net/NG/"+large_ng_dates[i]+"_small.gif";
  large_ng_button_hover[i] = new Image(25, 20);
  large_ng_button_hover[i].src = "//oil-price.net/TABLE2/static/hover_"+large_ng_dates[i]+".png";
  large_ng_buttons[i] = new Image(25, 20);
  large_ng_buttons[i].src = "//oil-price.net/TABLE2/static/button_"+large_ng_dates[i]+".png";
  }
}
var large_ng_current_but=0;
function large_ng_showGraph(id){
 document.getElementById("large_ng_button_"+large_ng_current_but).src=large_ng_buttons[large_ng_current_but].src;
 document.getElementById("large_ng_graph").src=large_ng_graph[id].src;
 document.getElementById("large_ng_button_"+id).src=large_ng_button_hover[id].src;
 large_ng_current_but=id;
 return true;
};
document.writeln('<style>.oilpricenettable2 {border-collapse: separate; border-spacing: 2px;} .oilpricenettable2 td {padding:1px;}<\/style>');
document.writeln('<table class=\"oilpricenettable2\" summary=\"Crude oil and commodity prices (c) http://oil-price.net\" style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12px; background-color:#efefef; border-collapse: collapse; text-align: left; border: 1px solid #000000; padding:0px; border-spacing:0px;\">');
document.writeln('<tbody style=\"padding:0px;\">');
document.writeln('<tr style=\"padding:0px;\">');
document.writeln('<td style=\"padding:0px;\">');
document.writeln('<table class=\"oilpricenettable2\" style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12px; background-color:#efefef; text-align: left; border: 0px; padding:0px; \" width=\"100%\">');
document.writeln('<tbody style=\"padding:0px;\">');
document.writeln('<tr><td style=\"background-color:#cecfce; font-size: 18px; font-weight: bold; color: #000000; white-space: nowrap\" colspan=4 align=\"center\">');
document.writeln('<span style=\"color: #000000\">Natural Gas<\/span><\/td>');
document.writeln('<\/tr>');
document.writeln('<tr>');
document.writeln('<td style=\"font-size: 22px; font-weight: bold; color: #000000 text-align: left; white-space: nowrap\" >');
document.writeln('<span style=\"color: #000000\">$6.28<\/span>');
document.writeln('<\/td>');
document.writeln('<td style=\"font-size: 16px; font-weight: bold; color: red; text-align: left; white-space: nowrap\">');
document.writeln('&#9660;-0.46');
document.writeln('<\/td>');
document.writeln('<td>&nbsp; <\/td>');
document.writeln('<td style=\"font-size: 16px; font-weight: bold; color: red; text-align: left; white-space: nowrap\">');
document.writeln('-7.28%');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<tr><td style=\"font-size: 9px; font-weight: bold; color: #FFFFFF text-align: left; white-space: nowrap\" colspan=2>');
document.writeln('<span style=\"color: #000000\">2022.12.04 end-of-day<\/span>');
document.writeln('<\/td><\/tr>');
document.writeln('<\/tbody>');
document.writeln('<\/table>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<tr>');
document.writeln('<td>');
document.writeln('<table class=\"oilpricenettable2\" style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12px; background-color:#efefef; border-collapse: collapse; text-align: left; border: 0px; padding:0px\">');
document.writeln('<tbody style=\"padding:0px;\">');
document.writeln('<tr style=\"padding:0px;\" valign=center><td style=\"padding:0px;\" align=center >');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en#natural_gas_large\">');
document.writeln('<img style=\"border:0px;\" src=\"//oil-price.net/NG/1m_small.gif\" id=\"large_ng_graph\" >');
document.writeln('<\/a>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<tr>');
document.writeln('<td>');
document.writeln('<table class=\"oilpricenettable2\" style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12px; background-color:#efefef; border-collapse: collapse; text-align: left; border: 0px; padding:0px\" width=100% >');
document.writeln('<tbody style=\"padding:0px;\">');
document.writeln('<tr><td>');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en#natural_gas_large\" onMouseOver=\"large_ng_showGraph(0);\"><img style=\"border:0px;\" src=\"//oil-price.net/TABLE2/static/hover_1m.png\" id=\"large_ng_button_0\"><\/a>');
document.writeln('<\/td>');
document.writeln('<td>');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en#natural_gas_large\" onMouseOver=\"large_ng_showGraph(1);\"><img style=\"border:0px;\" src=\"//oil-price.net/TABLE2/static/button_1q.png\" id=\"large_ng_button_1\"><\/a>');
document.writeln('<\/td>');
document.writeln('<td>');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en#natural_gas_large\" onMouseOver=\"large_ng_showGraph(2);\"><img style=\"border:0px;\" src=\"//oil-price.net/TABLE2/static/button_1y.png\" id=\"large_ng_button_2\"><\/a>');
document.writeln('<\/td>');
document.writeln('<td>');
document.writeln('<a target=\"_blank\" href=\"http://oil-price.net/dashboard.php?lang=en#natural_gas_large\" onMouseOver=\"large_ng_showGraph(3);\"><img style=\"border:0px;\" src=\"//oil-price.net/TABLE2/static/button_5y.png\" id=\"large_ng_button_3\"><\/a>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<\/tbody>');
document.writeln('<\/table>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<\/tbody>');
document.writeln('<\/table>');
document.writeln('<\/td>');
document.writeln('<\/tr>');
document.writeln('<\/tbody>');
document.writeln('<\/table>');

